# Generated by Django 2.2.5 on 2020-02-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
