# Generated by Django 2.2.5 on 2020-02-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_auto_20200209_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addr',
            new_name='address',
        ),
    ]
